deployment:
  tasks:
    - export NVM_DIR="$HOME/.nvm"
    - "[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm"
    - nvm use 20
    - yarn build
    - export DEPLOYPATH=/home/mehmetu/public_html/
    - /bin/cp -R dist $DEPLOYPATH
