name: Auto Tag and Relase

on:
  push:
    branches:
      - main # Ana branch'in adını değiştir, eğer farklıysa

jobs:
  auto_tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.new_tag.outputs.TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine new tag
        id: new_tag
        run: |
          NEW_TAG="v$(date +%s)"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
  release:
    runs-on: ubuntu-latest
    needs: auto_tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.auto_tag.outputs.new_tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Archive production artifacts
        run: zip -r release.zip dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.auto_tag.outputs.new_tag }}
          files: release.zip
