name: Auto Tag and Push

on:
  push:
    branches:
      - main # Ana branch'in adını değiştir, eğer farklıysa

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Önceki commitleri de alabilmesi için

      - name: Determine new tag
        id: new_tag
        run: |
          NEW_TAG="v$(date +%s)"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
